[workspace]
resolver = "1"

members = [
	"prelude",
	"create_map",
	"webui",
	"adjudicator",
]

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
