[package]
name = "prelude"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = { path = "../../petgraph" }
serde = { version = "1.0.171", features = ["derive", "rc"] }
serde_json = "1.0.100"
tokio = "1.29.1"
svg = "0.13.1"
eyre = "0.6.8"
itertools = "0.8.0"
surrealdb = "1.0.0-beta.9"
